import pandas as pd
person = pd.read_csv('doit_pandas/data/survey_person.csv')
site = pd.read_csv('doit_pandas/data/survey_site.csv')
survey = pd.read_csv('doit_pandas/data/survey_survey.csv')
visited = pd.read_csv('doit_pandas/data/survey_visited.csv')
visited_subset = visited.loc[[0, 2, 6], :]
o2o_merge = pd.merge(site, visited, left_on='name', right_on='site')
o2o_merge_left = pd.merge(site, visited, left_on='name', right_on='site', how = 'left')
o2o_merge_right = pd.merge(site, visited, left_on='name', right_on='site', how = 'right')
o2o_merge_outer = pd.merge(site, visited, left_on='name', right_on='site', how = 'outer')
o2o_merge_inner = pd.merge(site, visited, left_on='name', right_on='site', how = 'inner')
o2o_concat = pd.concat([site, visited], join = 'inner')
o2o_concat_outer = pd.concat([site, visited], join = 'outer')
print(site)
print(visited)
print(o2o_merge_outer)
print(o2o_merge_inner)
exit()
# print(o2o_merge)
print(o2o_concat)
print(o2o_concat_outer)
# print(o2o_merge_left)
# print(o2o_merge_right)
